version: '3'

services:
  pandoc:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: bash pandoc.sh
    container_name: pandoc
    image: pandoc
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    working_dir: /app
    volumes:
      - .:/app
  context:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_context
    container_name: contex
    image: context
    command: Katabuchi_CV.tex
    #command: test.tex
    #command: --version
    depends_on:
      - "pandoc"
    working_dir: /app
    volumes:
      - .:/app